Repository openkruise/rollouts, pull requests merged in 2022-11, with the labels that each got.

#98 Rollout even if workload revision is not changed
  api/v1alpha1/batchrelease_plan_types.go
  config/crd/bases/rollouts.kruise.io_batchreleases.yaml
  pkg/controller/batchrelease/batchrelease_event_handler.go
  pkg/controller/batchrelease/batchrelease_status.go
  pkg/controller/batchrelease/batchrelease_util.go
  pkg/controller/batchrelease/workloads/cloneset_control_plane.go
  pkg/controller/batchrelease/workloads/cloneset_controller.go
  pkg/controller/batchrelease/workloads/deployment_canary_control_plane.go
  pkg/controller/batchrelease/workloads/deployment_canary_controller.go
  pkg/controller/batchrelease/workloads/workload_rollout_control_plane.go
  pkg/controller/rollout/batchrelease/batchrelease.go
  pkg/controller/rollout/batchrelease/inner_batchrelease.go
  pkg/controller/rollout/canary.go
  pkg/controller/rollout/status.go
  pkg/util/controller_finder.go
  pkg/util/pod_utils.go
  test/e2e/rollout_test.go
  test/e2e/test_data/rollout/cloneset.yaml
Labels: size/L, lgtm, approved

#101 Allow to set toleration threshold for failure pods
  api/v1alpha1/batchrelease_plan_types.go
  api/v1alpha1/rollout_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rollouts.kruise.io_batchreleases.yaml
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  pkg/controller/batchrelease/workloads/cloneset_control_plane.go
  pkg/controller/batchrelease/workloads/commons.go
  pkg/controller/batchrelease/workloads/commons_test.go
  pkg/controller/batchrelease/workloads/deployment_canary_control_plane.go
  pkg/controller/batchrelease/workloads/statefulset_like_controller.go
  pkg/controller/batchrelease/workloads/workload_rollout_control_plane.go
  pkg/controller/rollout/batchrelease/inner_batchrelease.go
  pkg/util/pod_utils.go
  test/e2e/rollout_test.go
Labels: lgtm, approved, size/XL

#86 Implementing a generic Ingress based on Lua And A/B Testing Release
  .lift.toml
  Dockerfile
  Dockerfile_multiarch
  api/v1alpha1/rollout_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  lua_configuration/trafficrouting_ingress/aliyun-alb.lua
  lua_configuration/trafficrouting_ingress/nginx.lua
  pkg/controller/rollout/rollout_controller.go
  pkg/controller/rollout/status.go
  pkg/controller/rollout/trafficrouting.go
  pkg/controller/rollout/trafficrouting/gateway/gateway.go
  pkg/controller/rollout/trafficrouting/gateway/gateway_test.go
  pkg/controller/rollout/trafficrouting/ingress/ingress.go
  pkg/controller/rollout/trafficrouting/ingress/ingress_test.go
  pkg/controller/rollout/trafficrouting/interface.go
  pkg/controller/rollout/trafficrouting/nginx/nginx.go
  pkg/util/configuration/configuration.go
  pkg/util/lua_configuration.go
  pkg/util/luamanager/json.go
  pkg/util/luamanager/lua.go
  pkg/util/luamanager/lua_test.go
  pkg/util/meta.go
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  pkg/webhook/rollout/validating/rollout_create_update_handler_test.go
  test/e2e/rollout_test.go
  test/e2e/test_data/rollout/rollout-configuration.yaml
Labels: size/XXL, lgtm, approved
