Repository openkruise/rollouts, pull requests merged in 2022-07, with the labels that each got.

#53 Use full revision name for StatefulSet
  pkg/controller/batchrelease/workloads/unified_workload_control_plane.go
  pkg/util/pod_utils.go
  pkg/util/workloads_utils.go
  test/e2e/rollout_test.go
Labels: lgtm, approved, size/M

#56 kruise-rollout changelog 0.1.1
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#57 rollout v0.2.0 changelog
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#59 fix some little rollout bug
  pkg/controller/batchrelease/batchrelease_event_handler.go
  pkg/controller/rollout/trafficrouting.go
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  test/e2e/rollout_test.go
  test/e2e/test_data/gateway/httproute-test.yaml
Labels: lgtm, approved, size/S
