Repository openkruise/rollouts, pull requests merged in 2022-06, with the labels that each got.

#38 update rollout types in basic_usage
  docs/tutorials/basic_usage.md
Labels: lgtm, approved, size/XS

#34 Rollout Support StatefulSet & Advanced StatefulSet
  .github/workflows/e2e-1.19.yaml
  .github/workflows/e2e-1.23.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  main.go
  pkg/controller/batchrelease/batchrelease_controller.go
  pkg/controller/batchrelease/batchrelease_controller_test.go
  pkg/controller/batchrelease/batchrelease_event_handler.go
  pkg/controller/batchrelease/batchrelease_plan_executor.go
  pkg/controller/batchrelease/batchrelease_special_cases_handler.go
  pkg/controller/batchrelease/workloads/cloneset_control_plane.go
  pkg/controller/batchrelease/workloads/cloneset_controller.go
  pkg/controller/batchrelease/workloads/cloneset_controller_test.go
  pkg/controller/batchrelease/workloads/deployment_double_control_plane.go
  pkg/controller/batchrelease/workloads/deployment_double_controller.go
  pkg/controller/batchrelease/workloads/statefulset_like_controller.go
  pkg/controller/batchrelease/workloads/unified_workload_control_plane.go
  pkg/controller/batchrelease/workloads/workload_controller_types.go
  pkg/controller/rollout/batchrelease/inner_batchrelease.go
  pkg/controller/rollout/context.go
  pkg/controller/rollout/rollout_controller.go
  pkg/controller/rollout/rollouts_workload_event_handler.go
  pkg/controller/rollout/status.go
  pkg/controller/rollout/trafficrouting.go
  pkg/controller/rollout/trafficrouting/nginx/nginx.go
  pkg/util/client/client.go
  pkg/util/client/delegating_client.go
  pkg/util/client/no_deepcopy_lister.go
  pkg/util/controller_finder.go
  pkg/util/pod_utils.go
  pkg/util/util.go
  pkg/util/workloads_utils.go
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  pkg/webhook/rollout/validating/rollout_create_update_handler_test.go
  pkg/webhook/workload/mutating/webhooks.go
  pkg/webhook/workload/mutating/workload_update_handler.go
  pkg/webhook/workload/mutating/workload_update_handler_test.go
  test/e2e/batchrelease_test.go
  test/e2e/rollout_test.go
  test/e2e/test_data/batchrelease/sts.yaml
  test/e2e/test_data/rollout/advanced_statefulset.yaml
  test/e2e/test_data/rollout/headless_service.yaml
  test/e2e/test_data/rollout/native_statefulset.yaml
Labels: size/XXL, lgtm, approved

#44 Add Spec.RolloutID and CanaryStatus.ObservedRolloutID fields
  api/v1alpha1/rollout_types.go
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  pkg/controller/rollout/progressing.go
  pkg/controller/rollout/status.go
Labels: lgtm, approved, size/S

#43 Patch batchID label to pods during rollout
  api/v1alpha1/batchrelease_plan_types.go
  api/v1alpha1/batchrelease_types.go
  config/crd/bases/rollouts.kruise.io_batchreleases.yaml
  config/manager/manager.yaml
  pkg/controller/batchrelease/batchrelease_event_handler.go
  pkg/controller/batchrelease/batchrelease_plan_executor.go
  pkg/controller/batchrelease/batchrelease_special_cases_handler.go
  pkg/controller/batchrelease/workloads/cloneset_control_plane.go
  pkg/controller/batchrelease/workloads/deployment_double_control_plane.go
  pkg/controller/batchrelease/workloads/statefulset_like_controller.go
  pkg/controller/batchrelease/workloads/unified_workload_control_plane.go
  pkg/controller/rollout/batchrelease/inner_batchrelease.go
  pkg/controller/rollout/canary.go
  pkg/feature/switch.go
  pkg/util/controller_finder.go
  pkg/util/pod_utils.go
  pkg/util/util.go
  pkg/util/workloads_utils.go
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  test/e2e/rollout_test.go
  test/e2e/test_data/rollout/rollout_canary_base.yaml
Labels: lgtm, approved, size/XL

#45 Allow users set step.weight to 0
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
Labels: lgtm, approved, size/XS

#46 Ignore some cases that no need to progress.
  pkg/util/controller_finder.go
Labels: lgtm, approved, size/S

#47 Support dynamic watching for various workload types.
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/patch_manifests.yaml
  pkg/controller/batchrelease/batchrelease_controller.go
  pkg/controller/rollout/rollout_controller.go
  pkg/util/controller_finder.go
  pkg/util/util.go
  pkg/util/workloads_utils.go
  pkg/webhook/workload/mutating/webhooks.go
  pkg/webhook/workload/mutating/workload_update_handler.go
Labels: size/L, lgtm, approved

#48 Consider the indirect owner-relationship between pod and workload
  pkg/controller/batchrelease/workloads/statefulset_like_controller.go
  pkg/util/controller_finder.go
  pkg/util/pod_utils.go
  pkg/util/workloads_utils.go
  test/e2e/rollout_test.go
Labels: lgtm, approved, size/M

#50 Do not copy labels/annotations/finalizers to canary deployment
  pkg/controller/batchrelease/workloads/deployment_double_controller.go
Labels: lgtm, approved, size/S
