Repository openkruise/rollouts, pull requests merged in 2022-03, with the labels that each got.

#11 add credit for vela
  README.md
Labels: lgtm, approved, size/XS

#8 webhook
  webhook/add_rollout.go
  webhook/add_workload.go
  webhook/rollout/validating/rollout_create_update_handler.go
  webhook/rollout/validating/rollout_create_update_handler_test.go
  webhook/rollout/validating/webhooks.go
  webhook/server.go
  webhook/util/configuration/configuration.go
  webhook/util/controller/webhook_controller.go
  webhook/util/generator/certgenerator.go
  webhook/util/generator/fake/certgenerator.go
  webhook/util/generator/selfsigned.go
  webhook/util/generator/util.go
  webhook/util/util.go
  webhook/util/writer/atomic/atomic_writer.go
  webhook/util/writer/certwriter.go
  webhook/util/writer/error.go
  webhook/util/writer/fs.go
  webhook/util/writer/secret.go
  webhook/workload/mutating/webhooks.go
  webhook/workload/mutating/workload_update_handler.go
  webhook/workload/mutating/workload_update_handler_test.go
Labels: size/XXL, lgtm, approved

#6 rollout controller
  Makefile
  api/v1alpha1/rollout_types.go
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  config/default/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  controllers/rollout/batchrelease/batchrelease.go
  controllers/rollout/batchrelease/inner_batchrelease.go
  controllers/rollout/batchrelease/types.go
  controllers/rollout/canary.go
  controllers/rollout/context.go
  controllers/rollout/finalizer.go
  controllers/rollout/progressing.go
  controllers/rollout/rollout_controller.go
  controllers/rollout/rollout_controller_test.go
  controllers/rollout/rollouts_workload_event_handler.go
  controllers/rollout/rollouts_workload_event_handler_test.go
  controllers/rollout/status.go
  controllers/rollout/trafficrouting.go
  controllers/rollout/trafficrouting/nginx/nginx.go
  controllers/rollout/trafficrouting/trafficroutingutil.go
  go.mod
  go.sum
  main.go
  pkg/util/client.go
  pkg/util/condition.go
  pkg/util/controller_finder.go
  pkg/util/util.go
  pkg/util/workloads_utils.go
  test/e2e/rollout_test.go
  test/e2e/suite_test.go
  test/e2e/test_data/rollout/deployment.yaml
  test/e2e/test_data/rollout/nginx_ingress.yaml
  test/e2e/test_data/rollout/rollout_canary_base.yaml
  test/e2e/test_data/rollout/service.yaml
Labels: size/XXL, lgtm, approved

#9 batchrelease controller
  controllers/batchrelease/batchrelease_controller.go
  controllers/batchrelease/batchrelease_controller_test.go
  controllers/batchrelease/batchrelease_event_handler.go
  controllers/batchrelease/batchrelease_event_handler_test.go
  controllers/batchrelease/batchrelease_plan_executor.go
  controllers/batchrelease/batchrelease_special_cases_handler.go
  controllers/batchrelease/batchrelease_util.go
  controllers/batchrelease/workloads/cloneset_control_plan.go
  controllers/batchrelease/workloads/cloneset_controller.go
  controllers/batchrelease/workloads/cloneset_controller_test.go
  controllers/batchrelease/workloads/deployment_double_control_plan.go
  controllers/batchrelease/workloads/deployment_double_controller.go
  controllers/batchrelease/workloads/deployment_double_controller_test.go
  controllers/batchrelease/workloads/workload_controller_types.go
  go.mod
  main.go
  test/e2e/batchrelease_test.go
  test/e2e/test_data/batchrelease/cloneset.yaml
  test/e2e/test_data/batchrelease/cloneset_number_100.yaml
  test/e2e/test_data/batchrelease/cloneset_percentage_100.yaml
  test/e2e/test_data/batchrelease/cloneset_percentage_50.yaml
  test/e2e/test_data/batchrelease/deployment.yaml
  test/e2e/test_data/batchrelease/deployment_number_100.yaml
  test/e2e/test_data/batchrelease/deployment_percentage_100.yaml
  test/e2e/test_data/batchrelease/deployment_percentage_50.yaml
  test/images/image_utils.go
Labels: size/XXL, lgtm, approved

#20 Add workflow actions and update Makefile
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yaml
  .github/workflows/license.yml
  .golangci.yml
  Makefile
  OWNERS
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/_.yaml
  config/crd/bases/rollouts.kruise.io_batchreleases.yaml
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  go.mod
  go.sum
  pkg/controller/batchrelease/batchrelease_controller_test.go
  pkg/controller/rollout/rollouts_workload_event_handler_test.go
  pkg/util/controller_finder.go
  test/e2e/rollout_test.go
Labels: size/L, lgtm, approved

#21 Add licenses and fix manifests generation
  .license/README.md
  .license/dependency_decisions.yml
  Makefile
Labels: lgtm, approved, size/M

#22 Improve BatchRelease controller
  Dockerfile
  api/v1alpha1/batchrelease_plan_types.go
  api/v1alpha1/batchrelease_types.go
  api/v1alpha1/rollout_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rollouts.kruise.io_batchreleases.yaml
  pkg/controller/batchrelease/batchrelease_controller.go
  pkg/controller/batchrelease/batchrelease_controller_test.go
  pkg/controller/batchrelease/batchrelease_event_handler.go
  pkg/controller/batchrelease/batchrelease_plan_executor.go
  pkg/controller/batchrelease/batchrelease_special_cases_handler.go
  pkg/controller/batchrelease/batchrelease_util.go
  pkg/controller/batchrelease/workloads/cloneset_control_plan.go
  pkg/controller/batchrelease/workloads/cloneset_controller.go
  pkg/controller/batchrelease/workloads/cloneset_controller_test.go
  pkg/controller/batchrelease/workloads/deployment_double_control_plan.go
  pkg/controller/batchrelease/workloads/deployment_double_controller.go
  pkg/controller/batchrelease/workloads/deployment_double_controller_test.go
  pkg/controller/batchrelease/workloads/workload_controller_types.go
  pkg/util/workloads_utils.go
  temp
  test/e2e/batchrelease_test.go
  test/e2e/test_data/batchrelease/cloneset_number_100.yaml
Labels: size/XXL, lgtm, approved

#23 Allow modification of steps during rollout
  Dockerfile
  api/v1alpha1/rollout_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  pkg/controller/rollout/batchrelease/batchrelease.go
  pkg/controller/rollout/batchrelease/inner_batchrelease.go
  pkg/controller/rollout/batchrelease/types.go
  pkg/controller/rollout/canary.go
  pkg/controller/rollout/context.go
  pkg/controller/rollout/progressing.go
  pkg/controller/rollout/progressing_test.go
  pkg/controller/rollout/rollout_controller_test.go
  pkg/controller/rollout/status.go
  pkg/controller/rollout/trafficrouting.go
  pkg/controller/rollout/trafficrouting/nginx/nginx.go
  pkg/controller/rollout/trafficrouting/trafficroutingutil.go
  pkg/util/controller_finder.go
  pkg/util/util.go
  pkg/util/workloads_utils.go
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  pkg/webhook/rollout/validating/rollout_create_update_handler_test.go
  pkg/webhook/workload/mutating/workload_update_handler.go
  pkg/webhook/workload/mutating/workload_update_handler_test.go
  test/e2e/rollout_test.go
  test/e2e/test_data/rollout/cloneset.yaml
  test/e2e/test_data/rollout/deployment.yaml
  test/e2e/test_data/rollout/nginx_ingress.yaml
  test/e2e/test_data/rollout/rollout_canary_base.yaml
  test/e2e/test_data/rollout/service.yaml
Labels: size/XXL, lgtm, approved

#24 rollout docs
  README.md
  docs/getting_started/installation.md
  docs/getting_started/introduction.md
  docs/images/approve_rollout.png
  docs/images/continuous_release.png
  docs/images/deploy_rollout.png
  docs/images/echoserver_application.png
  docs/images/rollback_echoserver.png
  docs/images/rollout_canary.png
  docs/images/upgrade_echoserver.png
  docs/images/upgrade_failed.png
  docs/tutorials/basic_usage.md
Labels: size/L, lgtm, approved
