Repository openkruise/rollouts, pull requests merged in 2023-12, with the labels that each got.

#184 v1beta1 apis proposals
  api/v1alpha1/conversion.go
  api/v1alpha1/deployment_types.go
  api/v1beta1/batchrelease_plan_types.go
  api/v1beta1/batchrelease_types.go
  api/v1beta1/rollout_types.go
  api/v1beta1/trafficrouting.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/rollouts.kruise.io_batchreleases.yaml
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_batchreleases.yaml
  config/crd/patches/webhook_in_rollouts.yaml
  docs/proposals/20231107-v1beta1-apis.md
  lua_configuration/convert_test_case_to_lua_object.go
  lua_configuration/networking.istio.io/VirtualService/testdata/rollout_with_three_steps.yaml
  lua_configuration/networking.istio.io/VirtualService/trafficRouting.lua
  pkg/controller/batchrelease/batchrelease_controller.go
  pkg/controller/batchrelease/batchrelease_controller_test.go
  pkg/controller/batchrelease/batchrelease_event_handler.go
  pkg/controller/batchrelease/batchrelease_executor.go
  pkg/controller/batchrelease/control/canarystyle/deployment/control_test.go
  pkg/controller/batchrelease/control/partitionstyle/cloneset/control_test.go
  pkg/controller/batchrelease/control/partitionstyle/daemonset/control_test.go
  pkg/controller/batchrelease/control/partitionstyle/deployment/control_test.go
  pkg/controller/batchrelease/control/partitionstyle/statefulset/control_test.go
  pkg/controller/deployment/deployment_controller_test.go
  pkg/controller/deployment/rolling.go
  pkg/controller/deployment/sync.go
  pkg/controller/deployment/util/deployment_util.go
  pkg/controller/deployment/util/deployment_util_test.go
  pkg/controller/rollout/rollout_canary.go
  pkg/controller/rollout/rollout_canary_test.go
  pkg/controller/rollout/rollout_controller.go
  pkg/controller/rollout/rollout_controller_test.go
  pkg/controller/rollout/rollout_event_handler.go
  pkg/controller/rollout/rollout_progressing.go
  pkg/controller/rollout/rollout_progressing_test.go
  pkg/controller/rollout/rollout_status_test.go
  pkg/controller/trafficrouting/trafficrouting_controller.go
  pkg/trafficrouting/manager.go
  pkg/trafficrouting/manager_test.go
  pkg/trafficrouting/network/customNetworkProvider/custom_network_provider.go
  pkg/trafficrouting/network/customNetworkProvider/custom_network_provider_test.go
  pkg/trafficrouting/network/gateway/gateway.go
  pkg/trafficrouting/network/gateway/gateway_test.go
  pkg/trafficrouting/network/ingress/ingress.go
  pkg/trafficrouting/network/ingress/ingress_test.go
  pkg/trafficrouting/network/interface.go
  pkg/util/controller_finder.go
  pkg/util/rollout_utils.go
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  pkg/webhook/rollout/validating/rollout_create_update_handler_test.go
  pkg/webhook/rollout/validating/validate_v1alphal_rollout.go
  pkg/webhook/server.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/crd/crd.go
  pkg/webhook/workload/mutating/workload_update_handler.go
  pkg/webhook/workload/mutating/workload_update_handler_test.go
Labels: size/XXL, lgtm, approved

#188 webhook validate v1beta1 rollout
  config/webhook/manifests.yaml
  pkg/controller/rollout/rollout_canary.go
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  pkg/webhook/rollout/validating/rollout_create_update_handler_test.go
  pkg/webhook/rollout/validating/webhooks.go
  test/e2e/rollout_test.go
Labels: lgtm, approved, size/M

#189 dump to v1beta1 gatewayapis
  api/v1alpha1/rollout_types.go
  api/v1alpha1/trafficrouting_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/rollout_types.go
  api/v1beta1/zz_generated.deepcopy.go
  go.mod
  go.sum
  main.go
  pkg/controller/rollout/rollout_canary_test.go
  pkg/controller/rollout/rollout_controller_test.go
  pkg/controller/rollout/rollout_progressing_test.go
  pkg/controller/rollouthistory/rollouthistory_controller_test.go
  pkg/controller/trafficrouting/trafficrouting_controller_test.go
  pkg/trafficrouting/network/gateway/gateway.go
  pkg/trafficrouting/network/gateway/gateway_test.go
  pkg/trafficrouting/network/ingress/ingress.go
  pkg/trafficrouting/network/ingress/ingress_test.go
  pkg/util/controller_finder.go
  pkg/util/luamanager/lua_test.go
  test/e2e/rollout_test.go
  test/e2e/suite_test.go
  test/e2e/test_data/crds/httproutes.yaml
Labels: size/XXL, lgtm, approved

#167 fix gateway print log panic
  pkg/trafficrouting/network/gateway/gateway.go
Labels: lgtm, approved, size/XS

#185 Wait grace period seconds after pod creation/upgrade when traffic rolling
  pkg/trafficrouting/manager.go
  pkg/trafficrouting/manager_test.go
Labels: lgtm, approved, size/S

#176 Set default advanced deployment strategy
  pkg/controller/batchrelease/control/partitionstyle/deployment/control.go
  pkg/webhook/workload/mutating/workload_update_handler.go
Labels: lgtm, approved, size/XS

#190 rollout v0.5.0 changelog
  CHANGELOG.md
  Dockerfile_multiarch
  api/v1beta1/rollout_types.go
  config/crd/bases/rollouts.kruise.io_rollouts.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  go.mod
  pkg/webhook/server.go
Labels: size/L, lgtm, approved

#191 bugfix: Filter rs that are not part of the current Deployement
  pkg/controller/deployment/deployment_controller.go
Labels: lgtm, approved, size/S

#193 Refresh observed rollout-id for BatchRelease
  pkg/controller/batchrelease/batchrelease_status.go
Labels: lgtm, approved, size/XS
