Repository openkruise/rollouts, pull requests merged in 2023-05, with the labels that each got.

#134 Bringing progress delivery capability to Kruise Advanced DaemonSet workload
  api/v1alpha1/groupversion_info.go
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  pkg/controller/batchrelease/batchrelease_controller.go
  pkg/controller/batchrelease/batchrelease_event_handler.go
  pkg/controller/batchrelease/batchrelease_executor.go
  pkg/controller/batchrelease/control/canarystyle/deployment/canary.go
  pkg/controller/batchrelease/control/partitionstyle/daemonset/control.go
  pkg/controller/batchrelease/control/partitionstyle/daemonset/control_test.go
  pkg/controller/batchrelease/control/util.go
  pkg/controller/batchrelease/labelpatch/filter.go
  pkg/controller/rollout/rollout_controller.go
  pkg/controller/rollout/rollout_progressing.go
  pkg/util/controller_finder.go
  pkg/util/feature/feature_gate.go
  pkg/util/parse_utils.go
  pkg/util/rollout_utils.go
  pkg/util/workloads_utils.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
  pkg/webhook/workload/mutating/webhooks.go
  pkg/webhook/workload/mutating/workload_update_handler.go
  pkg/webhook/workload/mutating/workload_update_handler_test.go
Labels: size/XXL, lgtm, approved

#142 [feature]When the data type of spec.replicas is int, cancel the upper limit
  pkg/webhook/rollout/validating/rollout_create_update_handler.go
  pkg/webhook/rollout/validating/rollout_create_update_handler_test.go
Labels: lgtm, approved, size/S

#143 Add DaemonSet e2e test
  .github/workflows/e2e-daemonset-1.19.yaml
  .github/workflows/e2e-daemonset-1.23.yaml
  test/e2e/rollout_test.go
  test/e2e/test_data/rollout/daemonset.yaml
  test/e2e/test_data/rollout/rollout_canary_daemonset_base.yaml
  test/e2e/test_data/rollout/rollout_canary_daemonset_interrupt.yaml
Labels: lgtm, approved, size/XL

#146 Exclude workload deleted matching labels in webhook.
  go.mod
  go.sum
  pkg/webhook/util/matcher.go
  pkg/webhook/workload/mutating/workload_update_handler.go
  pkg/webhook/workload/mutating/workload_update_handler_test.go
Labels: lgtm, approved, size/XL
