Repository openkruise/rollouts, pull requests merged in 2025-04, with the labels that each got.

#251 support batch id label for canary strategy
  pkg/controller/batchrelease/control/canarystyle/control_plane.go
  pkg/controller/batchrelease/control/canarystyle/deployment/canary.go
  pkg/controller/batchrelease/control/canarystyle/deployment/control.go
  pkg/controller/batchrelease/control/canarystyle/deployment/control_test.go
  pkg/controller/batchrelease/control/canarystyle/interface.go
Labels: lgtm, approved, size/M

#261 Fix: blue-green batch-id e2e fails sometime
  .github/workflows/e2e-v1beta1-bluegreen-1.19.yaml
  .github/workflows/e2e-v1beta1-bluegreen-1.23.yaml
  pkg/controller/batchrelease/batchrelease_executor.go
  pkg/controller/batchrelease/control/bluegreenstyle/control_plane.go
  pkg/controller/batchrelease/control/canarystyle/control_plane.go
  pkg/controller/batchrelease/control/interface.go
  pkg/controller/batchrelease/control/partitionstyle/control_plane.go
  test/e2e/rollout_v1beta1_test.go
Labels: size/L, lgtm, approved

#265 Fix order of object in batchrelease event handler
  pkg/controller/batchrelease/batchrelease_event_handler.go
Labels: lgtm, approved, size/XS
